# Generated by Django 4.2.5 on 2023-10-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_company_address_alter_company_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="article",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
