# Generated by Django 4.2.5 on 2023-10-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_alter_company_company_type_delete_companytype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="alternatives",
            field=models.ManyToManyField(blank=True, null=True, to="website.company"),
        ),
        migrations.AlterField(
            model_name="company",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, to="website.companycategory"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="has_affiliate_program",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="homepage_screenshot",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="one_liner_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
