# Generated by Django 4.2.5 on 2023-10-02 01:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_rename_one_liner_description_company_one_liner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["name"], "verbose_name_plural": "Companies"},
        ),
    ]
