$(".sliderOne").length &&
    tns({
        container: ".sliderOne",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderOneControls",
        responsive: { 768: { items: 2 }, 990: { items: 3 } },
    });
$(".sliderTwo").length &&
    tns({
        container: ".sliderTwo",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderTwoControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderThree").length &&
    tns({
        container: ".sliderThree",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderThreeControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderFour").length &&
    tns({
        container: ".sliderFour",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderFourControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderFive").length &&
    tns({
        container: ".sliderFive",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderFiveControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderSix").length &&
    tns({
        container: ".sliderSix",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderSixControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderSeven").length &&
    tns({
        container: ".sliderSeven",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderSevenControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderEight").length &&
    tns({
        container: ".sliderEight",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderEightControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderNine").length &&
    tns({
        container: ".sliderNine",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderNineControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderTen").length &&
    tns({
        container: ".sliderTen",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderTenControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderEleven").length &&
    tns({
        container: ".sliderEleven",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderElevenControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderTweleve").length &&
    tns({
        container: ".sliderTweleve",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderTweleveControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderThirteen").length &&
    tns({
        container: ".sliderThirteen",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderThirteenControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderFourteen").length &&
    tns({
        container: ".sliderFourteen",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderFourteenControls",
        responsive: { 720: { items: 1 }, 940: { items: 2 } },
    });
$(".sliderFifteen").length &&
    tns({
        container: ".sliderFifteen",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderFifteenControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderSixteen").length &&
    tns({
        container: ".sliderSixteen",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderSixteenControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });
$(".sliderSeventeen").length &&
    tns({
        container: ".sliderSeventeen",
        loop: !0,
        startIndex: 0,
        items: 1,
        nav: !1,
        autoplay: 0,
        swipeAngle: !1,
        speed: 400,
        autoplayButtonOutput: !1,
        mouseDrag: !0,
        lazyload: !0,
        gutter: 20,
        controlsContainer: "#sliderSeventeenControls",
        responsive: { 540: { items: 2 }, 720: { items: 5 }, 960: { items: 7 } },
    });